language: php

php:
  - 5.4
  - 5.5

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install
  - php composer.phar update
  - php composer.phar dump-autoload -o

script: phpunit tests